#updated 7/17/23, for use on all black prototype
pot_ranges: {pot0: 172.0, pot1: 175.0, pot2: 167.0, pot3: 198.0, pot4: 182.0, pot5: 176.0}

rosdistro: 'melodic

  '
roslaunch:
  uris: {host_robothand_hp_elitebook_840_g1__35523: 'http://robothand-HP-EliteBook-840-G1:35523/',
    host_robothand_hp_elitebook_840_g1__39951: 'http://robothand-HP-EliteBook-840-G1:39951/'}
rosversion: '1.14.13

  '
run_id: 5063ba5c-f0dd-11ec-9410-2babb065445d
serial_node: {baud: 9600, port: /dev/ttyACM0}
